//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Day
{
	private string report
	{
		get;
		set;
	}

	private int number
	{
		get;
		set;
	}

	private bool outside
	{
		get;
		set;
	}

	public virtual IEnumerable<Time_slot> l_timeSlot
	{
		get;
		set;
	}

	public virtual IEnumerable<Activity> l_activity
	{
		get;
		set;
	}

	public virtual IEnumerable<TimeUnit> l_tu
	{
		get;
		set;
	}

	public virtual Status Status
	{
		get;
		set;
	}

	public virtual int getNumber()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool getOutside()
	{
		throw new System.NotImplementedException();
	}

	public Day(int number)
	{
	}

	public virtual void display_schedule()
	{
		throw new System.NotImplementedException();
	}

	public void modifyActivity(Activity newActivity)
	{
		throw new System.NotImplementedException();
	}

}

