//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Mission
{
	private int howmanydays
	{
		get;
		set;
	}

	public virtual Day l_day
	{
		get;
		set;
	}

	public virtual Day getDay(int numDay)
	{
		throw new System.NotImplementedException();
	}

	public virtual void modifyDay(int numJour)
	{
		throw new System.NotImplementedException();
	}

	public Mission(int howmanydays)
	{
	}

	public virtual List<Places> getPlaces(Day start, Day end)
	{
		throw new System.NotImplementedException();
	}

	public virtual void beginMission(DateTime CurrentEarthDate)
	{
		throw new System.NotImplementedException();
	}

	public virtual void modifyStatus(Status newStatus)
	{
		throw new System.NotImplementedException();
	}

}

