//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Mission
{
	private int howmanydays
	{
		get;
		set;
	}

	private DateTime begniningDateEarth
	{
		get;
		set;
	}

	private list<> l_genericActivity
	{
		get;
		set;
	}

	public virtual Day l_day
	{
		get;
		set;
	}

	public virtual IEnumerable<Astronaut> l_astronaut
	{
		get;
		set;
	}

	public virtual IEnumerable<Place> l_place
	{
		get;
		set;
	}

	public virtual Day getDay(int numDay)
	{
		throw new System.NotImplementedException();
	}

	public virtual void modifyDay(int numJour)
	{
		throw new System.NotImplementedException();
	}

	public Mission(int howmanydays, DateTime beginningDateEatrh, list<Astronaut> l_astronaut)
	{
	}

	public virtual List<Places> getPlaces(Day start, Day end)
	{
		throw new System.NotImplementedException();
	}

	public virtual void beginMission(DateTime CurrentEarthDate)
	{
		throw new System.NotImplementedException();
	}

	public virtual void modifyStatus(Status newStatus)
	{
		throw new System.NotImplementedException();
	}

	public virtual list<> getListActivity()
	{
		throw new System.NotImplementedException();
	}

}

