//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Astronaut
{
	private string nom
	{
		get;
		set;
	}

	private string prenom
	{
		get;
		set;
	}

	public virtual IEnumerable<Activity> l_activity
	{
		get;
		set;
	}

}

