//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TimeUnit
{
	public virtual int index
	{
		get;
		set;
	}

	public virtual int nbMin
	{
		get;
		set;
	}

	public virtual string toString(int minInt)
	{
		throw new System.NotImplementedException();
	}

}

