//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Activity
{
    private string description;
	public  string description {get; set; }

    private string type;
	public string Type { get; set; }

    private List<Astronaut> l_astronaut;
	public List<Astronaut> L_astronaut{ get;set;}

    private Place place;
	public Place Place{get;set;} 

    private int start;
	public int Start{get;set;}

    private int end;
	public int End{get;set;}

	public Activity(int start, int end, string type = "private")
	{
        //choose the place in a list / with the map. If it's not there, create it
        Place = new Place(0.0, 0.0, "base");
	}

}

