//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Day
{
    //properties
	private string report;
    public string Report { get; set; }

	private int number;
    public int Number { get; }


	private bool outside;
    public bool Outside { get; set; }


	public virtual List<Activity> l_activity { get; set; }

    //constructor

    public Day(int number)
    {
        for (int i = 0; i < 148; i++)
        {
            //to adapt with schedule 
            l_activity[i] = new Inside();
        }
    }

    //methodes
    public virtual int getNumber()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool getOutside()
	{
		throw new System.NotImplementedException();
	}


	public virtual void display_schedule()
	{
		throw new System.NotImplementedException();
	}

	public void modifyActivity(Activity newActivity)
	{
		throw new System.NotImplementedException();
	}

}

