//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Day
{
    //properties
	private string report;
    public string Report { get; set; }

	private int number;
    public int Number { get; }


	private bool outside;
    public bool Outside { get; set; }


	private List<Activity> l_activity;
    public List<Activity> L_activity { get; }

    //constructor

    public Day(int number)
    {
        for (int i = 0; i < 148; i++)
        {
            //to adapt with schedule 
            l_activity[i] = new Inside();
        }
    }

    //methodes

	public virtual void display_schedule()
	{
		throw new System.NotImplementedException();
	}

    //don't mind what you remove
    public void addActivity(Activity newActivity)
    {
        for (int i = newActivity.Start; i <= newActivity.End; i++)
        {
            l_activity[i] = newActivity;
        }
    }

	public void rmActivity(Activity prevActivity)
	{
        foreach (Activity act in l_activity)
        {
            if (act.Equals(prevActivity))
            {
                Activity newActivity = new Inside(prevActivity.Start, prevActivity.End);
                addActivity(newActivity);
            }
            else
            {
                //message erreur
            }
        }
	}

}

