//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Inside : Activity
{
    public Inside(int _start, int _end string _type = "private") : base(_start, _end, new Place(0.0,0.0,"HQ", _hq_x, _hq_y), _type) { }
    

}

