//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Inside : Activity
{
    public Inside(int _start, int _end, Place map_hq, string _type = "private") : base(_start, _end, map_hq, _type) { }
    

}

