//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Past : Day
{
    public Past(int _number, int _hq_x, int _hq_y) : base(_number, _hq_x, _hq_y) { }
	public virtual string getReport()
	{
		throw new System.NotImplementedException();
	}

}

